2 카테고리별 분류 UI 퍼블리싱
DSM-SOGONG-MZ-SANGSIC/MZ-iOS pull request #4
Opened 2024-05-01 03:16 UTC by DSMInhyeKang

## 개요
> 카테고리별 분류(메인) UI 퍼블리싱

## 작업사항
- [x] 카테고리별 분류(메인) UI 퍼블리싱

## UI
<img src="https://github.com/DSM-SOGONG-MZ-SANGSIC/MZ-iOS/assets/101160430/6c51dae1-72f1-4c16-918d-146a837817f8" width="150px"></img>

2024-05-01 03:45 UTC, BJCHO0501 requested changes

2024-05-01 03:45 UTC, BJCHO0501 commented on App/Sources/Scene/Category/CategoryViewModel.swift
> +    var categories = BehaviorRelay<[String]>(value: ["어휘", "역사(인물)", "역사(사건)", "수학", "과학", "스포츠", "어휘", "역사(인물)", "역사(사건)", "수학", "과학", "스포츠"])
카테고리 enum으로 빼주고,
카테고리 데이터 collection에 bind 할때밖에 안쓰니까 cold observable 쓰는게 좋을거 같아요.

2024-05-12 15:56 UTC, BJCHO0501 commented on App/Resources/Asset.xcassets/mosaic.imageset/mosaic.png
이거 왜 넣은거에요

2024-05-12 15:56 UTC, BJCHO0501 commented on App/Sources/Scene/Category/CategoryViewController.swift
> +        ].forEach { contentBackView.addSubview($0) }
addSubViews라는거 만들었습니다. 그거 쓰시면 될거 같아요

2024-05-12 15:56 UTC, BJCHO0501 commented on App/Sources/Scene/Category/Component/CategoryCell.swift
> +        ].forEach { self.addSubview($0) }
addSubViews로 변경해주세요

2024-05-12 15:56 UTC, BJCHO0501 commented on App/Sources/Scene/Category/Component/CategoryCell.swift
> +            cornerRadius: self.layer.cornerRadius).cgPath
이거 무슨 코드인지 설명해주실 수 있나요
없을때랑 있을때랑 차이가 없는거 같은데

2024-05-13 00:01 UTC, DSMInhyeKang commented on App/Resources/Asset.xcassets/mosaic.imageset/mosaic.png
<img width="419" alt="스크린샷 2024-05-13 오전 9 01 29" src="https://github.com/DSM-SOGONG-MZ-SANGSIC/MZ-iOS/assets/101160430/53550c36-93e9-4e84-840a-00071b936b20">

2024-05-13 00:09 UTC, DSMInhyeKang commented on App/Sources/Scene/Category/Component/CategoryCell.swift
> +            cornerRadius: self.layer.cornerRadius).cgPath
그냥 layer에 shadow 지정했을 때 view hierarchy에서 렌더링 비용 때문에 
optimization opportunities 뜨는데 UIBezierPath 사용하면 그런 워닝이 안 떠요

2024-05-13 01:20 UTC, BJCHO0501 commented on App/Resources/Asset.xcassets/mosaic.imageset/mosaic.png
이거 디자인에 넣을 사진 없어서 저렇게 표시된거 같은데 나중에 사진 넣을거여서 삭제해도 될거 같아요

2024-05-13 02:13 UTC, DSMInhyeKang commented on App/Resources/Asset.xcassets/mosaic.imageset/mosaic.png
<img width="200" src="https://github.com/DSM-SOGONG-MZ-SANGSIC/MZ-iOS/assets/101160430/f216d7df-2a25-4e8d-a737-db73a7bb5b83">

그럼 이미지 빼고 그냥 컬러로 넣어놓을게요

2024-05-13 02:23 UTC, DSMInhyeKang commented on App/Sources/Scene/Category/CategoryViewController.swift
> +        ].forEach { contentBackView.addSubview($0) }
<img width="200" src="https://github.com/DSM-SOGONG-MZ-SANGSIC/MZ-iOS/assets/101160430/7dd98e27-5784-48ea-9fbe-9c4d7448903d">

에셋에 이미지 들어가 있는 거 빼고 systemImage("circle.fill')로 바꿔놨습니다

2024-05-13 02:24 UTC, BJCHO0501 approved these changes

2024-05-13 02:24 UTC, DSMInhyeKang commented on App/Sources/Scene/Category/CategoryViewController.swift
> +        ].forEach { contentBackView.addSubview($0) }
<img width="200" src="https://github.com/DSM-SOGONG-MZ-SANGSIC/MZ-iOS/assets/101160430/7dd98e27-5784-48ea-9fbe-9c4d7448903d">

에셋에 이미지 들어가 있는 거 빼고 systemImage("circle.fill")로 바꿔놨어요

2024-05-13 02:25 UTC, merged